version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  depassement-de-tampon.cyrhades.fr:
    image: anssi/fcsc2022-pwn-depassement-de-tampon:latest
    ports:
      - ${PORT_SSH}:4000